### ISSUE TITLE
Field mapping for translating  sigma rules to elastalert rules

### ISSUE THREAD

**Issue by aminemirat** [Cargill/OpenSIEM-Logstash-Parsing#15]
Hi everyone
thanks for this great project, I want to know if you have a field mapping for translating sigma rules to elastalert rules .
thanks in advance

**Comment by brian-grabau** [comment]
We have not worked with elastalert can you point me to schema or more detail as to what you are referring too

**Comment by brian-grabau** [comment]
Ah I see https://github.com/SigmaHQ/sigma
Yes mapping events to miter is on our back log, so ya we will look into this and would welcome help from the community.

**Comment by aminemirat** [comment]
thanks for your reply, so if you could tell me  what is the field that mention  "cat /etc/shadow" in this project

**Comment by nnovaes** [comment]
> Hi everyone
> thanks for this great project, I want to know if you have a field mapping for translating sigma rules to elastalert rules .
> thanks in advance

which version of ES and which version of elastalert are you using?

**Comment by brian-grabau** [comment]
ECS is 1.7 but working on moving to 1.9

**Comment by brian-grabau** [comment]
And we have index templates in Docs so I don't this matters what version of Elastic you use

**Comment by brian-grabau** [comment]
https://opensearch.org/docs/latest/security-analytics/index/
Opensearch has released a feature for SIGMA rule support.

**Comment by brian-grabau** [comment]
OpenSearch supports SIGMA rules and they have created mappings between ECS and OCSF (which is the schema OpenSearch supports for SIMA rules) We are looking at moving from ECS to OCSF in a 2.0 release.
