### ISSUE TITLE
Add fields in all configs to enable coverage report

### ISSUE THREAD

**Issue by KrishnanandSingh** [Cargill/OpenSIEM-Logstash-Parsing#172]
## User Story - details
If every parsing config has log.source.hostname field and event.dataset then from elastic/kibana we can create coverage report per host.

## Tasks
- [ ]
- [ ]

## Related Code
```
<< Any related code here... >>
```

**Comment by verbecee** [comment]
This issue has been resolved by adding kafka.topic and event.module to all configurations. Closing! Thanks, Krishna.
