### ISSUE TITLE
Mcafee EPO  Logstash Pattern  required

### ISSUE THREAD

**Issue by loloprime** [Cargill/OpenSIEM-Logstash-Parsing#290]

**Comment by loloprime** [comment]
sample format


<190>1 2000-02-22T06:05:02.0Z stoan Eeents - Fwd [agentInfo@2342 tenantId="1" bpsId="1" tenantGUID="0000-000-0000-000-0000000}" tenantNodePath="1\1"] ?<?xml version="1.0" encoding="UTF-8"?><SCORData><MachineInfo><MachineName>loloutj</MachineName><AgentGUID>{12279999330288}</AgentGUID><IPAddress>10.10.10.10</IPAddress><OSName>Windows 8</OSName><UserName>admin</UserName><TimeZoneBias>-543</TimeZoneBias><RawMACAddress></RawMACAddress></MachineInfo><SCORSoftware ProductName="mcafee fire" ProductVersion="1.1.1.1" ProductFamily="mcafee"><SCOREvent><EventID>1234</EventID><Severity>100</Severity><GMTTime>2000-01-20T05:26:00</GMTTime><SCORevent_name>Access_DENIED</SCORevent_name><SCORevt_id>128</SCORevt_id><SCORevt_type>CAT_TYPE</SCORevt_type><SCORevt_sink>920</SCORevt_sink><SCORseq_no>89032134</SCORseq_no><SCORtime_stamp>165003993882</SCORtime_stamp><SCORserver_state>10</SCORserver_state><SCORuser_name>SBB390\SSTAuto1</SCORuser_name><SCORprocess_name>C:\Windows\System32\findme.exe</SCORprocess_name><SCORprocess_id>43326</SCORprocess_id><SCORreputation_score>31</SCORreputation_score><SCORparent_process_name>C:\Windows\System32\joke.exe</SCORparent_process_name><SCORfile_name>C:\WINDOWS\system32\lose.txt</SCORfile_name><SCORfile_sha1>123278387387829</SCORfile_sha1><SCORfile_md5>2738927392932</SCORfile_md5><SCORfile_sha256>03yu2ii2o33739292d0020</SCORfile_sha256><SCORfile_type>shellt</SCORfile_type><SCORdeny_reason>grok me</SCORdeny_reason><SCORdeny_reason_code>200</SCORdeny_reason_code></SCOREvent></SCORSoftware></SCORData>

**Comment by brian-grabau** [comment]
MSN covers EPO but we may split it out

**Comment by brian-grabau** [comment]
Sorry for the delay https://github.com/Cargill/OpenSIEM-Logstash-Parsing/blob/1.0/config/processors/syslog_audit_trellix.epo.conf covers your request.
